name: LLM Code Reviewer (Commit & PR)

on:
  push:
    branches:
      - "**"
  pull_request_target: # <-- 将 pull_request 改为 pull_request_target
    types: [opened, synchronize]
    branches:
      - "**"

jobs:
  llm-review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        # 注意：使用 pull_request_target 时，如果直接 checkout PR 的 head ref，
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }} # 确保 checkout PR 的最新提交

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install openai pygithub httpx

      - name: Run LLM Review Script
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
          LLM_API_KEY: ${{ secrets.LLM_DEEPSEEK_TOKEN }}
        run: |
          python scripts/llm_review.py